- name: Instalamos los paquetes de NFS
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - nfs-utils
    - net-tools
- name: Crear el directorio nfs
  file:
    path: /mnt/nfs
    state: directory
    owner: root
    group: root
    mode: 0644
- name: fichero exportfs
  lineinfile:
    dest: /etc/exports
    line: "/mnt/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.k8 }}"

# habilitamos el servicio nfs
- name: Habilitar NFS
  service:
    name: nfs-server
    state: started
    enabled: yes
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.nfs }}"
#exportacion del directorio creado y comprobación
- name: Exportar nfs
  become: yes
  command: exportfs -r
  
- name: exportfs -s
  command: exportfs -s
# añadirmos el servicio al fw y lo reiniciamos
- name: Añadir servicio al firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - nfs
    - rpc-bind
    - mountd
- name: Reinicio del servicio fw
  systemd:
    name: firewalld
    state: reloaded