- name: Instalamos los paquetes de NFS
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - nfs-utils
    - net-tools
  
- name: Crear el directorio nfs en el servidor
  file:
    path: /mnt/nfs
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items: "{{ groups.nfs}}"

- name: fichero exportfs
  lineinfile:
    dest: /etc/exports
    line: "/mnt/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.nfs }}"

# habilitamos el servicio nfs
- name: Habilitar NFS
  service:
    name: nfs-server
    state: started
    enabled: yes
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.nfs }}"
#exportacion del directorio creado y comprobación
- name: Exportar nfs
  become: yes
  command: exportfs -r
  
- name: exportfs -s
  command: exportfs -s
# creamos el punto de montaje en los clientes
- name: crear punto montaje
  file:
    path: /mnt/nfs
    state: directory
    owner: azureuser
    group: azureuser
    mode: '0775'
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.k8 }}"
# montamos el volumen
- name: montar volumen NFS
  mount:
    src: 10.0.1.11:/nfs/ssd/shared_data
    path: /mnt/nfs
    opts: rw,sync,hard
    state: mounted
    fstype: nfs

# añadirmos los servicios al fw y lo reiniciamos
- name: Añadir servicio al firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - nfs
    - rpc-bind
    - mountd
- name: Reinicio del servicio fw
  systemd:
    name: firewalld
    state: reloaded