- name: Instalamos los paquetes de NFS
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - nfs-utils
    - net-tools
# habilitamos el servicio nfs
- name: Habilitar NFS
  service:
    name: nfs-server
    state: started
    enabled: yes
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.nfs }}"

# creamos y exportamos el recurso NFS
- name: Crear el directorio nfs en el servidor
  file:
    path: /mnt/nfs
    state: directory
    owner: azureuser
    group: azureuser
    mode: 0644
  with_items: "{{ groups.nfs}}"

# Declaración del recurso que vamos a exportar
- name: fichero exportfs
  lineinfile:
    dest: /etc/exports
    line: "/mnt/nfs/ 10.0.1.0/16 (rw,sync,all_squash)"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.nfs }}"

#exportacion del directorio creado y comprobación
- name: Exportar nfs
  command: exportfs -r

# añadirmos los servicios al fw y lo reiniciamos
- name: Añadir servicio al firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - nfs
    - rpc-bind
    - mountd
- name: Reinicio del servicio fw
  systemd:
    name: firewalld
    state: reloaded

# Instalación y configuración de los clientes
# creamos el punto de montaje en los clientes
- name: crear punto montaje
  file:
    path: /mnt/nfs
    state: directory
    owner: azureuser
    group: azureuser
    mode: '0775'
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.k8 }}"
# montamos el volumen en los clientes
#- name: montar volumen NFS
#  mount:
#    src: 10.0.1.12:/mnt/nfs
#    path: /mnt/nfs
#    opts: rw,sync,hard
#    state: mounted
#    fstype: nfs
#  when: hostvars[item].ansible_host is defined
#  with_items: "{{ groups.k8 }}"

- name: fichero fstab
  lineinfile:
    dest: /etc/fstab
    line: "10.0.1.12:/mnt/nfs /mnt/nfs  nfs defaults  0 0"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.k8 }}"

- name: montamos el volumen
  command: mount -a
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.k8 }}"