#Instalaci칩n del servidor NFS para ofrecer almacenamiento al cluster de kubernetes.
- name: Instalamos los paquetes de NFS y arrancamos el servicio
  become: true  
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - nfs-utils
    - net-tools

#Creamos directorio a compartir con los permisos necesarios
- name: Crear el directorio nfs
  file:
    path: /mnt/nfs
    state: directory
    owner: root
    group: root
    mode: 0644
  become: true  

# Modirifamos el fichero exports para incluir los servidores
- name: crear/modificar fichero /etc/exports
  lineinfile:
    path: /etc/exports
    line: '{{item}}'
    loop:
      - '/mnt/nfs	10.0.1.10(rw,sync)'
      - '/mnt/nfs	10.0.1.11(rw,sync)'
      - '/mnt/nfs	10.0.1.12(rw,sync)'
  
# habilitamos el servicio nfs
- name: Habilitar NFS
  service:
    name: nfs-server
    state: started
    enabled: yes

#exportacion del directorio creado y comprobaci칩n
- name: Exportar nfs
  become: yes
  command: exportfs -r

- name: exportfs -s
  command: exportfs -s

# a침adirmos el servicio al fw y lo reiniciamos
- name: A침adir servicio al firewalld
  become: true
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop: 
    - nfs
    - rpc-bind
    - mountd

- name: Reinicio del servicio fw 
  systemd:
    name: firewalld
    state: reloaded
  become: yes