- name: Configuramos el hostname
  lineinfile:
    dest: /etc/hosts
    line: "{{item}}"
    state: present
  become: true
  with_items: 
    - "10.0.1.10 master {{inventory_hostname}}.{{kubernets_domain}}"
    - "10.0.1.12 worker1 {{inventory_hostname}}.{{kubernets_domain}}"
    - "10.0.1.11 nfs {{inventory_hostname}}.{{kubernets_domain}}"


