    # Variables necesarias para la instalación del master
    k8s_cni: calico                                      
    container_runtime: cri-o                             
    pod_network_cidr: "192.168.0.0/16"