---

- name: Activar masquerade y reinicar fw
  hosts: all:!nfs
  tasks:
    - name: Activate transparent masquerade
      become: yes
      modprobe:
        name: br_netfilter
        state: present

    - name: Añadir al fw
      firewalld:
        masquerade: yes
        state: enabled
        permanent: yes

    - name: reiniciar servicio firewalld
      become: yes
      systemd: 
        name: firewalld
        state: reloaded
    
    - name: k8s firewall traffic
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content:
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: apply changes
      become: true
      command: sysctl --system

    - name: disable swap
      become: true
      shell: swapoff -a