
# Autorizar el acceso al cluster
- name: crear directorio /azureuser/.kube
  file:
    path: /home/azureuser/.kube
    mode: 0755
    state: directory
    
- name: Copiando /etc/kubernetes/admin.conf a /home/azureuser/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/azureuser/.kube/config
    remote_src: yes
    owner: azureuser
    group: azureuser
    mode: 0644

- name: comprobar nodos
  command: kubectl get nodes
  register: nodoscluser

- name: Mostrando la salida de los nodos del cluster
  debug:
    msg: "{{ nodoscluster.stdout_lines }}"

