- name: get ingress_controller_port
  script: getPort.py "{{ ingress_controller_info_path }}"
  args:
    executable: python3
  changed_when: no
  register: ingress_controller_port

- name: check ingress controller port
  delegate_to: localhost
  wait_for:
    host: "{{ hostvars[inventory_hostname].ansible_host }}"
    port: "{{ ingress_controller_port.stdout | int }}"
    timeout: 5
  register: ingress_controller_port_check
  ignore_errors: yes

