---

- name: puertos para nodo master k8
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250-10252/tcp
    - 10255/tcp

- name: recargar firewalld 
  systemd:
    name: firewalld
    state: reloaded  

  