# Permitir el tráfico necesario
- name: puertos para nodo master k8
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250-10252/tcp
    - 10255/tcp

- name: recargar firewalld 
  systemd:
    name: firewalld
    state: reloaded  

# Permitir conexiones desde los worker
- name: allow access to workers
  become: true
  firewalld:
      rich_rule: "{{item}}"
      permanent: yes
      immediate: yes
      state: enabled
  loop:
   - 'rule family=ipv4 source address=10.0.1.10/24 accept'
   - 'rule family=ipv4 source address=10.0.1.11/24 accept'

- name: reiniciar servicio firewalld
  become: true
  systemd: 
   name: firewalld
   state: reloaded

# configuración de kubeadm
- name: Configurando Kubeadmin
  become: true
  command: kubeadm config images pull

# instalar plugin cni  
- name: Instalar el plugin CNI
  command: 'kubeadm init --pod-network-cidr 192.168.0.0/16'

- name: crear directorio /root/.kube
  file:
    path: /root/.kube
    mode: 0644
    state: directory
    
- name: Copiando /etc/kubernetes/admin.conf a /root/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    mode: 0644



# Exportar configuración de kubeadmin

# Autorizar acceso al clúster

  