- name: Preparacion del cluster
  hosts: all
  become: true
  vars_files:
    - "group_vars/comunes.yml"
  gather_facts: true
  roles:
    - 1-prerequisitos

- name: Instalacion cluster kubernete
  hosts: all
  become: true
  vars_files:
    - "group_vars/comunes.yml"
    - "group_vars/k8.yml"
  gather_facts: true
  roles:
    - 2-instalacion-k8

- name: configuracion master
  hosts: master
  gather_facts: true
  become: true
  roles:
    - 3-master

- name: configuracion worker
  hosts: worker
  become: true
  vars_files:
    - "group_vars/worker.yml"
  gather_facts: true
  roles:
    - 4-worker

- name: Instalacion NFS
  hosts: nfs
  gather_facts: true
  become: true
  roles:
    - 5-nfs

- name: Despliegue Nginx con nfs
  hosts: worker
  gather_facts: true
  become: true
  roles:
    - 6-aplicacion
