- name: Preparacion del cluster
  hosts: all
  vars_files:
    - "group_vars/common.yaml"
  gather_facts: true
  roles:
    - prerequisitos

- name: Instalacion cluster kubernete
  hosts: all
  vars_files:
    - "group_vars/common.yaml"
  gather_facts: true
  roles:
    - instalacion-k8