---
- name: Preparacion del cluster
  hosts: all
  become: true
  vars_files:
    - "group_vars/comunes.yml"
  gather_facts: true
  roles:
    - 1-prerequisitos

- name: Instalacion NFS
  hosts: all
  gather_facts: true
  become: true
  roles:
    - 2-nfs-server

- name: Instalacion cluster kubernete
  hosts: all
  become: true
  vars_files:
    - "group_vars/comunes.yml"
    - "group_vars/k8.yml"
  gather_facts: true
  roles:
    - 3-instalacion-k8

- name: configuracion master
  hosts: master
  gather_facts: true
  become: true
  roles:
    - 4-master

- name: configuracion worker
  hosts: worker
  become: true
  vars_files:
    - "group_vars/worker.yml"
  gather_facts: true
  roles:
    - 5-worker
    
- name: Despliegue Nginx con nfs
  hosts: master
  gather_facts: true
  become: true
  vars_files:
    - "group_vars/app.yml"
  roles:
    - 6-aplicacion
