---
- name: Crear namespace nginx
  command:  kubectl create namespace nginx

- name: Copiando los archivos necesarios para la aplicación
  copy:
    src: "{{ item }}"
    dest: "/home/azureuser/{{ item }}"
    mode: '0644'
  with_items:
    - "{{ files }}"
  
  ## Desplegando los volumenes y nginx ##
- name: Desplegando nginx y sus pv/pvc
  command: "kubectl apply -f {{ item }}"
  with_items:
    - "{{ files }}"

# Comprobamos que el despliegue ha sido correcto
- name: Ejecutando kubectl get nodes
  shell: kubectl get nodes
  register: kubectl_out
  
- name: Mostramos el resultado de kubectl get nodes
  debug:
    msg: "{{ kubectl_out.stdout_lines }}"

- name: Ejecutando kubectl get pods A
  shell: kubectl get pods -A -o wide
  register: kubectl_pods
  
- name: Mostramos el resultado de kubectl get pods A
  debug:
    msg: "{{ kubectl_pods.stdout_lines }}"
  
- name: Ejecutando kubectl get namespaces
  shell: kubectl get namespaces
  register: kubectl_name
  
- name: Mostramos el resultado de kubectl get namespaces
  debug:
    msg: "{{ kubectl_name.stdout_lines }}"
  
- name: Ejecutando kubectl get pv
  shell: kubectl get pv
  register: kubectl_pv
  
- name: Mostramos el resultado de kubectl get pv
  debug:
    msg: "{{ kubectl_pv.stdout_lines }}"

- name: Ejecutando kubectl get pvc
  shell: kubectl get pvc
  register: kubectl_pvc
  
- name: Mostramos el resultado de kubectl get pvc
  debug:
    msg: "{{ kubectl_pvc.stdout_lines }}"